### ISSUE TITLE
Can we download the entire branch?

### ISSUE THREAD

**Issue by danypr92** [coopdevs/odoo-role#22]
With the argument `depth: 1` Git only clone 1 commit, but we need the entire branch.

https://github.com/coopdevs/odoo-role/blob/0f6d2a6ab0d1f611b15f525f01e28ac34cf45774/tasks/download.yml#L23

**Comment by raneq** [comment]
We implemented an alternative download strategy since [v0.0.7](https://github.com/coopdevs/odoo-role/releases/tag/v0.0.7), although git strategy is still available.

We are [still cloning 1 commit](https://github.com/coopdevs/odoo-role/releases/tag/v0.0.7), should we clone the whole history, @danypr92 ?

Otherwise we can close this issue

**Comment by danypr92** [comment]
Yes @raneq, I also think that we can close this issue.
